name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install packages
        run: |
          sudo apt install g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 mingw-w64-tools
          
      - name: List directories
        run: |
          ls -R > ls.txt
          ls -R /usr > ls-user.txt
          ls -R /usr/bin > ls-user-bin.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-artifact
          path: ${{github.workspace}}/ls.txt
          if-no-files-found: ignore
          retention-days: 0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-artifact-user
          path: ${{github.workspace}}/ls-user.txt
          if-no-files-found: ignore
          retention-days: 0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-artifact-user-bin
          path: ${{github.workspace}}/ls-user-bin.txt
          if-no-files-found: ignore
          retention-days: 0
